import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type StepInput from "@ui5/webcomponents/dist/StepInput.js";
declare const _default: Meta<StepInput>;
export default _default;
export declare const Basic: UI5StoryArgs<StepInput, StoryArgsSlots>;
export declare const Readonly: UI5StoryArgs<StepInput, StoryArgsSlots>;
export declare const Disabled: UI5StoryArgs<StepInput, StoryArgsSlots>;
export declare const Design: UI5StoryArgs<StepInput, StoryArgsSlots>;
export declare const MinMax: UI5StoryArgs<StepInput, StoryArgsSlots>;
export declare const ValuePrecision: UI5StoryArgs<StepInput, StoryArgsSlots>;
export declare const Label: UI5StoryArgs<StepInput, StoryArgsSlots>;
