import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Table from "@ui5/webcomponents/dist/Table.js";
declare const _default: Meta<Table>;
export default _default;
export declare const BasicTable: UI5StoryArgs<Table, StoryArgsSlots>;
export declare const TableDisplayInline: UI5StoryArgs<Table, StoryArgsSlots>;
export declare const TableStickyHeader: UI5StoryArgs<Table, StoryArgsSlots>;
export declare const TableNoData: UI5StoryArgs<Table, StoryArgsSlots>;
export declare const GrowingTableMoreButton: UI5StoryArgs<Table, StoryArgsSlots>;
export declare const GrowingTableScroll: UI5StoryArgs<Table, StoryArgsSlots>;
export declare const GroupingTableSelect: UI5StoryArgs<Table, StoryArgsSlots>;
