import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Switch from "@ui5/webcomponents/dist/Switch.js";
declare const _default: Meta<Switch>;
export default _default;
export declare const Basic: UI5StoryArgs<Switch, StoryArgsSlots>;
export declare const WithText: UI5StoryArgs<Switch, StoryArgsSlots>;
export declare const Checked: UI5StoryArgs<Switch, StoryArgsSlots>;
export declare const Disabled: UI5StoryArgs<Switch, StoryArgsSlots>;
export declare const Design: UI5StoryArgs<Switch, StoryArgsSlots>;
