import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type MultiComboBox from "@ui5/webcomponents/dist/MultiComboBox.js";
declare const _default: Meta<MultiComboBox>;
export default _default;
export declare const BasicMultiComboBox: UI5StoryArgs<MultiComboBox, StoryArgsSlots>;
export declare const MultiComboBoxItems: UI5StoryArgs<MultiComboBox, StoryArgsSlots>;
export declare const MultiComboBoxFreeTextInput: UI5StoryArgs<MultiComboBox, StoryArgsSlots>;
export declare const MultiComboBoxGroupingItems: UI5StoryArgs<MultiComboBox, StoryArgsSlots>;
