import type { Meta, StoryFn } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type RatingIndicator from "@ui5/webcomponents/dist/RatingIndicator.js";
declare const _default: Meta<RatingIndicator>;
export default _default;
export declare const BasicRatingIndicator: UI5StoryArgs<RatingIndicator, StoryArgsSlots>;
export declare const RatingIndicatorMax: UI5StoryArgs<RatingIndicator, StoryArgsSlots>;
export declare const DisabledRatingIndicator: StoryFn;
export declare const ReadonlyRatingIndicator: StoryFn;
