import type { Meta } from "@storybook/web-components";
import type Toolbar from "@ui5/webcomponents/dist/Toolbar.js";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
declare const _default: Meta<Toolbar>;
export default _default;
export declare const Basic: UI5StoryArgs<Toolbar, StoryArgsSlots>;
export declare const WithSpacer: UI5StoryArgs<Toolbar, StoryArgsSlots>;
export declare const WithSeparator: UI5StoryArgs<Toolbar, StoryArgsSlots>;
export declare const AlwaysOverflowItems: UI5StoryArgs<Toolbar, StoryArgsSlots>;
export declare const NeverOverflowItems: UI5StoryArgs<Toolbar, StoryArgsSlots>;
export declare const StartAlignedItems: UI5StoryArgs<Toolbar, StoryArgsSlots>;
