import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Button from "@ui5/webcomponents/dist/Button.js";
declare const _default: Meta<Button>;
export default _default;
export declare const Basic: UI5StoryArgs<Button, StoryArgsSlots>;
export declare const Disabled: UI5StoryArgs<Button, StoryArgsSlots>;
export declare const WithIconAndDesign: UI5StoryArgs<Button, StoryArgsSlots>;
export declare const WithEndIcon: UI5StoryArgs<Button, StoryArgsSlots>;
export declare const IconOnly: UI5StoryArgs<Button, StoryArgsSlots>;
