import type { Meta, StoryFn } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Input from "@ui5/webcomponents/dist/Input.js";
declare const _default: Meta<Input>;
export default _default;
export declare const Basic: UI5StoryArgs<Input, StoryArgsSlots>;
export declare const WithSuggestions: UI5StoryArgs<Input, StoryArgsSlots>;
export declare const SuggestionsWrapping: UI5StoryArgs<Input, StoryArgsSlots>;
export declare const WithValueStateMessage: UI5StoryArgs<Input, StoryArgsSlots>;
export declare const WithLabel: UI5StoryArgs<Input, StoryArgsSlots>;
export declare const WithValueHelpDialog: StoryFn;
