import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type RangeSlider from "@ui5/webcomponents/dist/RangeSlider.js";
declare const _default: Meta<RangeSlider>;
export default _default;
export declare const BasicRangeSlider: UI5StoryArgs<RangeSlider, StoryArgsSlots>;
export declare const RangeSliderCustomValues: UI5StoryArgs<RangeSlider, StoryArgsSlots>;
export declare const RangeSliderTooltip: UI5StoryArgs<RangeSlider, StoryArgsSlots>;
export declare const RangeSliderTickmarksCustomStep: UI5StoryArgs<RangeSlider, StoryArgsSlots>;
export declare const RangeSliderTickmarksTooltipLabel: UI5StoryArgs<RangeSlider, StoryArgsSlots>;
